### PR TITLE
Feature/extracting framework

### PR DESCRIPTION
**Pull request by bb-ceccles**
Removing the .Net code from the repository to allow it to be pulled in from the framework

https://github.com/buildingblocks/bb-prototype-website-razor-framework

### CODE REVIEW

**Comment by jimmah** [comment]
Hi Chris,

Whats the reasoning behind extracting this out of the prototype, are we going to reuse it somewhere?

Are we going to publish to nuget.org, or is it going onto our proget? If not, should it not just be a separate project in the same solution added as a `<ProjectReference/>` rather than `<PackageReference/>` (https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json-to-csproj#dependency-type).

Either way, can you migrate the framework project to the csproj version (`dotnet migrate`, or open in VS2017), and update the dependent packages to the same versions used in this project?

Cheers,
Jim

**Comment by jimmah** [comment]
Just looked through the issue list, is this intended to resolve #9?

**Review by jimmah — CHANGES_REQUESTED** [review]
Hi Chris,

~~Whats the reasoning behind extracting this out of the prototype, are we going to reuse it somewhere?~~

~~Are we going to publish to nuget.org, or is it going onto our proget? If not, should it not just be a separate project in the same solution added as a <ProjectReference/> rather than <PackageReference/> (https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json-to-csproj#dependency-type).~~

Edit: @rsleggett has explained the reasoning, and I agree.

Either way, can you migrate the framework project to the csproj version (dotnet migrate, or open in VS2017), and update the dependent packages to the same versions used in this project?

Cheers,
Jim

**Comment by bb-ceccles** [comment]
Hi Jim ,

Yes we need to migrate the frame work to the csproj which should allow the issues with git version step in TC to work. As at the moment the versioning needs to be done manually.

http://teamcity.building-blocks.com/viewType.html?buildTypeId=BuildingBlocksTridion_BbPrototypeWebsiteRazorFramework

We can also add features to the framework and easily allow it to be pulled in through an update to the nuget package having it as a seperate project. 

Chris

**Comment by jordanrobinson** [comment]
Yeah like Jim mentioned we kind of need it as csproj, since the project.json way of working can't even run in VS2017 now.

**Comment by bb-ceccles** [comment]
Closing pull request as new branch created from the new csproj version of the code.

https://github.com/buildingblocks/bb-prototype-website-razor/pull/18

**Pull request closed without merging**
